# Generated by Django 5.2.6 on 2025-09-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=10)),
                ('monthly_salary', models.FloatField(default=0.0)),
                ('approved_limit', models.FloatField(default=0.0)),
                ('current_debt', models.FloatField(default=0.0)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
