# Generated by Django 5.2.6 on 2025-09-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan',
            new_name='Loans',
        ),
    ]
