# Generated by Django 5.2.6 on 2025-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_loan_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_amount',
            field=models.FloatField(default=0),
        ),
    ]
